### ISSUE TITLE
Plug-in Crashes in Ubuntu

### ISSUE THREAD

**Issue by senrabdet** [muflone/remmina-plugin-rdesktop#6]
The version of Remmina in Ubuntu seems to have lost all sense of "seameless" and "Remoteapp".  Working from http://www.muflone.com/remmina-plugin-rdesktop/english/settings.html, I think I've managed to compile the "muflone" plugin successfully without errors.  Note, the plugin seems to get parked in a different location than Remmina 1.2.0-rcgit.14 stores its plugins at in my version on Ubutnut 16.04.  So when I start Remmina, the plug in doesn't show.  If I softlink or physically move the plugin where my Remmina stores it's plugins  (I tried /usr/lib/x86_64-linux-gnu/remmina/plugins), Remmina sees the plugin but crashes as soon as I try to create a profile.

When I try all of the options I've used before in the version of Remmina I've installed with it's native RDP plugin, I can connect to the server but none of the seamless .rdp's work.  This may be because I'm testing on a Win7 machine using Kim Knights registry tweaks, but the seameless approach works if I use xfreerdp from the command line.

I'm trying to access whether to keep at this - my end goal is to run seamless/Remote apps from Linux end points to windows servers running windows apps.

Suggestions?  Thanks!

**Comment by hyph3n** [comment]
I believe I'm encountering the same issue, so I'm adding some detail to the report above.

Kernel: 4.7.4-200.fc24.x86_64
Distro: Fedora 24
Desktop: Cinnamon

I followed the instructions provided for building the rdesktop plugin, but when I loaded Remmina, rdesktop was not listed. I found that the plugin had been installed to /usr/**lib**/remmina/plugins instead of /usr/**lib64**/remmina/plugins. I copied the file to the path under lib64, and this time when I started Remmina, rdesktop was listed. I configured an entry using the same connection details I have used previously with freerdp.

When I clicked on connect, it caused a segfault, killing Remmina.

Here's a backtrace:

<pre>
Thread 1 "remmina" received signal SIGSEGV, Segmentation fault.
0x00007ffff6973df6 in g_type_check_instance_cast () from /lib64/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff6973df6 in g_type_check_instance_cast () at /lib64/libgobject-2.0.so.0
#1  0x0000555555592530 in remmina_widget_pool_register ()
#2  0x00007fffd9f97ce6 in remmina_plugin_rdesktop_init () at /usr/lib64/remmina/plugins/remmina-plugin-rdesktop.so
#3  0x00005555555887a8 in remmina_protocol_widget_open_connection_real ()
#4  0x0000555555573cf5 in remmina_connection_window_open_from_file_full ()
#5  0x0000555555573d36 in remmina_connection_window_open_from_filename ()
#6  0x00007ffff694f3e5 in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#7  0x00007ffff6961432 in signal_emit_unlocked_R () at /lib64/libgobject-2.0.so.0
#8  0x00007ffff696a05f in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#9  0x00007ffff696a43f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#10 0x00007ffff784af76 in gtk_tree_view_multipress_gesture_pressed () at /lib64/libgtk-3.so.0
#11 0x00007ffff0ea9c58 in ffi_call_unix64 () at /lib64/libffi.so.6
#12 0x00007ffff0ea96ba in ffi_call () at /lib64/libffi.so.6
#13 0x00007ffff69500fa in g_cclosure_marshal_generic_va () at /lib64/libgobject-2.0.so.0
#14 0x00007ffff694f614 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#15 0x00007ffff6969dd9 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#16 0x00007ffff696a43f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#17 0x00007ffff76d32ab in gtk_gesture_multi_press_begin () at /lib64/libgtk-3.so.0
#18 0x00007ffff6952197 in g_cclosure_marshal_VOID__BOXEDv () at /lib64/libgobject-2.0.so.0
#19 0x00007ffff694f614 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#20 0x00007ffff6969dd9 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#21 0x00007ffff696a43f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#22 0x00007ffff76d023b in _gtk_gesture_check_recognized () at /lib64/libgtk-3.so.0
#23 0x00007ffff76d182b in gtk_gesture_handle_event () at /lib64/libgtk-3.so.0
#24 0x00007ffff76d442d in gtk_gesture_single_handle_event () at /lib64/libgtk-3.so.0
#25 0x00007ffff76a3f4e in gtk_event_controller_handle_event () at /lib64/libgtk-3.so.0
#26 0x00007ffff785a87b in _gtk_widget_run_controllers () at /lib64/libgtk-3.so.0
#27 0x00007ffff771a4ec in _gtk_marshal_BOOLEAN__BOXED () at /lib64/libgtk-3.so.0
#28 0x00007ffff694f3e5 in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#29 0x00007ffff696182d in signal_emit_unlocked_R () at /lib64/libgobject-2.0.so.0
#30 0x00007ffff6969b8f in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#31 0x00007ffff696a43f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#32 0x00007ffff785c9fc in gtk_widget_event_internal () at /lib64/libgtk-3.so.0
#33 0x00007ffff771775e in propagate_event () at /lib64/libgtk-3.so.0
#34 0x00007ffff7719692 in gtk_main_do_event () at /lib64/libgtk-3.so.0
#35 0x00007ffff72540c5 in _gdk_event_emit () at /lib64/libgdk-3.so.0
#36 0x00007ffff72810b2 in gdk_event_source_dispatch () at /lib64/libgdk-3.so.0
#37 0x00007ffff6f606ba in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#38 0x00007ffff6f60a70 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#39 0x00007ffff6f60d92 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#40 0x00007ffff7718815 in gtk_main () at /lib64/libgtk-3.so.0
#41 0x0000555555569e94 in main ()
</pre>

Let me know if there's anything else I can do to help resolve this issue (as I'm having difficulties with freerdp as well).

Thanks!

**Comment by Shogun8** [comment]
SAME!

**Comment by amirtal** [comment]
ubuntu 18.10
same:
plugin installs to '/usr/lib/remmina/plugins' 
if linked to '/usr/lib/x86_64-linux-gnu/remmina/plugins' ,trying to create a profile causes a crash.

**Comment by muflone** [comment]
this was fixed in v1.3.0.0
